name: build-nanopi-r4s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/rockchip/build.sh

      - name: Building NanoPi R4S Firmware
        run: |
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/rockchip/imm.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/rockchip/build.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE=friendlyarm_nanopi-r4s \
            -e ROOTFS_PARTSIZE=2048 \
            immortalwrt/imagebuilder:rockchip-armv8-openwrt-24.10.1 /bin/bash /home/build/immortalwrt/build.sh

      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done

      - name: Upload Firmware
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild
          name: ImmortWrt-NanoPi-R4S
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/*.img.gz
            ${{ github.workspace }}/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}